services:
  api:
    build:
      context: ./apps/api
    container_name: badminton-api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    environment:
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_SSL: ${DATABASE_SSL:-true}
      DATABASE_SSL_REJECT_UNAUTHORIZED: ${DATABASE_SSL_REJECT_UNAUTHORIZED:-false}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE:-true}
      FRONTEND_URL: ${ADMIN_WEB_URL:-http://160.25.81.212:5173/}
      CUSTOMER_FRONTEND_URL: ${CUSTOMER_WEB_URL:-http://160.25.81.212:5174/}
    ports:
      - "${PORT:-3000}:3000"

  web:
    build:
      context: ./apps/web
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    container_name: badminton-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "${FRONTEND_PORT:-5173}:80"

  customer-web:
    build:
      context: ./apps/customer-web
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    container_name: badminton-customer-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "${CUSTOMER_FRONTEND_PORT:-5174}:80"
